-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgzVyOQ8j9Olxujrl5
tliTWbyMCv1ngYLUqKH8miFe1bmgCgYIKoZIzj0DAQehRANCAATpGEyGa5iw5LbQ
TJpxRIzyfyI5UofJo0sWMDUP7vryC1RjipIfePTY0pQBLbAfpVnLD4RFSs5a3J3o
oOasKWDn
-----END PRIVATE KEY-----